name: Run the tests

on:
  workflow_dispatch:
    inputs:
      BASE_URL:
        description: 'Base URL for the tests'
        required: true
        default: 'https://www.myer.com.au'
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        playwright install chrome

    - name: Start Chrome in debug mode
      run: |
        google-chrome --user-data-dir=/tmp/chrome-user-data --remote-debugging-port=9222 --window-size=1280,720 --headless &
      shell: bash

    - name: Run tests
      env:
        BASE_URL: ${{ github.event.inputs.BASE_URL || 'https://www.myer.com.au' }}
      run: |
        source venv/bin/activate
        pytest -v -s  --html=report.html --self-contained-html

    - name: Upload test report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: report.html